service: aws-ruby-example

provider:
  name: aws
  runtime: ruby2.5
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    LINE_CHANNEL_SECRET: ${self:custom.lineChannelSecret.${self:provider.stage}}
    LINE_CHANNEL_ACCESS_TOKEN: ${self:custom.lineChannelAccessToken.${self:provider.stage}}

custom:
  defaultStage: dev
  lineChannelSecret:
    dev: ${file(./secret.yml):lineChannelSecret.dev}
    prod: ${file(./secret.yml):lineChannelSecret.prod}
  lineChannelAccessToken:
    dev: ${file(./secret.yml):lineChannelAccessToken.dev}
    prod: ${file(./secret.yml):lineChannelAccessToken.prod}

functions:
  handle:
    handler: handler.handle
    memorySize: 128
    events:
      - http:
          path: handle
          method: post
